// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ferlzxkdmbxfisdcwcrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlcmx6eGtkbWJ4ZmlzZGN3Y3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEyMDg3MTAsImV4cCI6MjA5Njc4NDcxMH0.Wr6Gt6Uc4owdFH5EzUmgvdypWWfjaC6oB7SpFMhcuy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});